### ISSUE TITLE
Error Loading Widget

### ISSUE THREAD

**Issue by shoesforindustry** [CalebGrove/content-viewer#4]
Call to a member function text() on boolean
/site/plugins/content-viewer/widget/widget.php
Line 7: if($page->$field()->value()->isNotEmpty()){

Multi-lingual Site
Kirby version: 2.5.7
PHP 7.0.25 

any ideas?

**Comment by calebgrove** [comment]
Nothing right off the top of my head. Could you put together a test for me to play with?

**Comment by calebgrove** [comment]
And have you modified the plugin at all? Line 7 should be `if($page->$field()->isNotEmpty()){`, not `if($page->$field()->value()->isNotEmpty()){`

**Comment by shoesforindustry** [comment]
Thanks, I tried that same error. No real example just download starter pack and add plugin, it  fails with the error above.

**Comment by calebgrove** [comment]
Could you try this?

Replace lines 9 and 10 of [content-viewer.php](https://github.com/calebgrove/content-viewer/blob/master/content-viewer.php) with:

~~~~ php
if(!site()->pages()->findBy('intendedTemplate', 'content-viewer')) {
	site()->pages()->create('content-viewer', 'content-viewer', array(
~~~~

All I've done is add `pages()` to the logic, and it seems to be working for me.
