### ISSUE TITLE
move widget over and make wider in panel

### ISSUE THREAD

**Issue by jklue** [CalebGrove/content-viewer#7]
Hi Caleb, Thank you soo much for making this publicly available. We always write client documentation by hand but I'm looking into modernizing that system.

I like my dashboard super simple, but the content-viewer widget isn't filling the available space. I'm going to add a lot of content to this widget, so I'd like it to move right and fill in the remaining space. (screenshot)
![screenshot_2018-09-18_11_16_03](https://user-images.githubusercontent.com/5399943/45697796-92c6dd80-bb34-11e8-9a97-03ba3da92951.png)

How could I go about doing this? Thank you!!

**Comment by calebgrove** [comment]
This would be nice, but I know of no documented way to do this. The layout is all handled automatically by Kirby (though you can [control the widget sorting](https://getkirby.com/docs/developer-guide/panel/widgets#sorting-widgets)).

**Comment by calebgrove** [comment]
If anyone knows of a way to control this, I would welcome the know-how.
